### ISSUE TITLE
Spot/On-Demand fallback documentation

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-issues#212]
I'd like to start using the spot/on-demand fallback option but I'm not seeing it in documentation (searching for "spot").  Any recommendations?

**Comment by ntabris** [comment]
So far just in the API docs: https://docs.coiled.io/user_guide/api.html?highlight=spot#coiled.BackendOptions

Need to add some better docs around this all. My current recommendation is

```
Cluster(..., backend_options={"spot":True, "spot_on_demand_fallback": True, "multizone": True})
```

**Comment by scharlottej13** [comment]
We've added https://docs.coiled.io/user_guide/cluster_creation.html#pricing-and-availability. The updated recommendation is `cluster = coiled.Cluster(use_best_zone=True, compute_purchase_option="spot_will_fallback")`.
