### ISSUE TITLE
A few more random pieces of feedback

### ISSUE THREAD

**Issue by cicdw** [coiled/coiled-issues#24]
- the icons for deleting a cluster are slightly confusing (when clicking fast I'm not sure whether clicking the red trashcan or the X is "confirming" my delete) 
- it seems that most of my clusters are stuck in a "stopping" state for many hours now, not sure why
- dashboard link should be more prominent

**Comment by dantheman39** [comment]
Thanks Chris!!

- I think in the short term we can at least add a tooltip around the trash icons indicating "confirm" or "cancel".
- We're looking into that :)
- Agreed!!

**Comment by mrocklin** [comment]
I wonder if just turning "running" into a link would be enough to attract
users' attention

**Comment by dantheman39** [comment]
@mrocklin  It already is a link :) , but it's not very visually salient, and it's also not obvious that if you click it you'll be taken to view the dashboard. We could throw the Visibiliy (eye) icon next to it and use that instead of a link.

**Comment by necaris** [comment]
@dantheman39 making it visually distinct and highlighting + underlining it (as links are generally on the web) would do the job IMHO and be visually simpler than another icon.

**Comment by mrocklin** [comment]
Icons are also welcome.  There are many ways here.

**Comment by dantheman39** [comment]
Going to close because I believe all of these have been addressed (for a while now!). Thank you for bringing them up!
