### ISSUE TITLE
Error when creating environment from YAML with pip packages

### ISSUE THREAD

**Issue by jose-moralez** [coiled/coiled-issues#28]
Hi. When trying to create an environment from a YAML file with pip packages in it I get the following error:

```
> coiled.create_software_environment(name='myenv', conda='env.yml')
Updating Software Environment ... -
{"message": "Solving conda environment..."}  
{"message": "Failed:\n\nInvalid spec 'None': Cannot match on field(s): {'pip'}"}  
{"message": "Invalid spec 'None': Cannot match on field(s): {'pip'}", "raise": true}  
```
I've used the helm chart before and I remember they were two different fields (conda packages and pip packages) not sure if this is related.

Here is the environment file I was using:
```
name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - dask
  - lightgbm
  - numpy
  - pandas
  - pip
  - scikit-learn
  - statsmodels
  - pip:
    - arch
    - supersmoother
```

**Comment by mrocklin** [comment]
Thanks for raising this issue @jose-moralez .

I believe that @jrbourbeau already has a fix for it that will go out with the next release.  (is that right @jrbourbeau ?)

**Comment by jrbourbeau** [comment]
Yep, that's correct! 

@jose-moralez support for `pip` package within a conda environment YAML file will be included in the next release

**Comment by jose-moralez** [comment]
Thank you for your quick response. I came across this issue on friday and checked the docs just now and saw the `pip` keyword argument in the `create_software_environment` method, I closed this after that because it solves my problem. However I see that it's not included in version `0.0.15`, is that part of the next release?

**Comment by jrbourbeau** [comment]
> is that part of the next release?

Yes, both the `pip=` keyword for `create_software_environment` and `pip` packages within a conda environment file are part of the next release. With `coiled==0.0.15` only conda packages and docker images are supported for creating software environments. I can be sure to ping you on this issue when we push out the next release : )

**Comment by mrocklin** [comment]
Yes :)

**Comment by jose-moralez** [comment]
Great. Thank you!

**Comment by jrbourbeau** [comment]
@jose-moralez we pushed out `coiled==0.0.16` earlier today, so you should be good to upgrade and start using `pip` packages!
