### ISSUE TITLE
Conda install on windows fails initial attempts, causing install time >20 minutes

### ISSUE THREAD

**Issue by therriault** [coiled/coiled-issues#41]
No idea if this is unique to my machine / configuration (Lenovo Yoga 910 running Windows 10, Python 3.7, Conda 4.8.3), but just wanted to share in case there's a solution you can include in the getting started docs, or a better approach to recommend. It did finally go through, but for whatever reason it took like 20 minutes of failing during those initial attempts before it finally figured it out. So if there's something that could be done to improve this situation (either on the conda-forge side or just by recommending pip for windows users) that would be helpful because it delayed the process of getting up and running significantly.

Here's the error messages I was getting before it finally started installing properly (at the bottom of the screenshot):

![image](https://user-images.githubusercontent.com/4842513/89824120-9e549080-db20-11ea-837f-df47d98ae6af.png)

**Comment by mrocklin** [comment]
Thanks for highlighting this Andrew.  I'll boot up Windows later this
afternoon and give things a whirl.  I'll check back here when things are
smoother.

**Comment by mrocklin** [comment]
I suspect that your local conda installation just has a lot of stuff in it
and that we introduce something that creates a hard-to-figure-out
dependency solve.

In this case I would generally recommend one of two solutions:

1.  Create a new conda environment (clean, but maybe not your normal
workflow)
2.  Install with pip (not clean, but probably easy)

**Comment by mrocklin** [comment]
@jrbourbeau maybe short term we only advertise the `coiled` pip package?

**Comment by jrbourbeau** [comment]
> but for whatever reason it took like 20 minutes

Sorry to hear that @therriault, thanks for letting us know

> maybe short term we only advertise the coiled pip package?

That seems reasonable if installing `coiled` frequently leads to long solve times. @mrocklin when you get a chance could you see how long it takes to conda install `coiled` into the `coiled/default` environment on Windows? It'd be good to get at least one more data point before removing `conda install coiled` from the docs

**Comment by necaris** [comment]
> @jrbourbeau maybe short term we only advertise the `coiled` pip package

I hope we don't have to -- it'd be nice if we could stick to one package manager to minimize confusion!
