### ISSUE TITLE
Read s3 data without IAM role

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-issues#44]
I'm on a machine with a AWS credentials and the quickstart isn't working for me.  I get the following error

```
OSError: s3://nyc-tlc/trip data/yellow_tripdata_2019-*.csv resolved to no files
```

When I add the keyword `storage_options={"anon": True}` to the read_csv call then things work ok.  Historically this was because our worker tasks didn't have sufficient permissions to read public data.  Is this still the case?  cc @necaris

**Comment by necaris** [comment]
@mrocklin can you point me at the task / cluster in question? On beta or sandbox?

**Comment by mrocklin** [comment]
mrocklin/win-play in beta

**Comment by necaris** [comment]
The task role assigned to those workers (and the scheduler) is https://console.aws.amazon.com/iam/home#/roles/mrocklin which has the S3 policy attached :-( so I'm not sure what's going on.

**Comment by dantheman39** [comment]
It seems like this has been resolved, closing. Feel free to reopen.
