### ISSUE TITLE
Add some flexibility around worker core limits

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-issues#46]
If you have a worker limit of 100 you might think that you could scale to 25 4-core machines.  Actually, this isn't the case, because the scheduler is there, taking up one core.  

I recommend that we add a 10% buffer to limits to allow for a little bit of flexibility.

cc @TomAugspurger @marcosmoyano

**Comment by necaris** [comment]
@mrocklin right now we actually have some code to ensure the scheduler cores are _included_ in the total count against which the limit is checked -- we could just remove it, if the goal is explicitly to limit **worker** cores.

**Comment by mrocklin** [comment]
I think that we should include scheduler cores generally.  (we open
ourselves up to people launching a lot of schedulers otherwise).  I'm in
favor of fudging by 10%.
