### ISSUE TITLE
Cluster HTML repr doesn't respect JupyterLab themes

### ISSUE THREAD

**Issue by gjoseph92** [coiled/coiled-issues#51]
Without ipywidgets installed, the HTML repr of a `coiled.Cluster` is hard to read in a dark theme:
![image](https://user-images.githubusercontent.com/3309802/90827131-e5007280-e2f8-11ea-9c61-b538bced859c.png)

Rather than hardcoding colors, you could pull them from CSS variables defined by the theme; something like

```css
background-color: var(--jp-cell-editor-background);
border: var(--jp-border-width) solid var(--jp-cell-editor-border-color);
display: inline-block;
padding: 10px;
```

(I'm sure there are canonically correct CSS variables to use here, I just grabbed whatever looked right.)

Using that produces:
![image](https://user-images.githubusercontent.com/3309802/90827137-e7fb6300-e2f8-11ea-9e3b-121c94c64e87.png)

![image](https://user-images.githubusercontent.com/3309802/90827324-488aa000-e2f9-11ea-9483-4c05b0631cf7.png)

Downside is that these variables don't work for classic notebooks, though there are probably some other variables (or fallbacks) you could use.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @gjoseph92!

We're inheriting this behavior from Dask's base `Cluster` class, so it not only impacts `coiled.Cluster`, but also other cluster managers like `distributed.LocalCluster` (screenshot below). If you don't mind, would you be okay opening an issue upstream in distributed's issue tracker as this impacts the broader Dask community (I tried to transfer this issue, but I am unable to transfer it out the `coiled` GitHub orgnaization)? I'm also happy to handle that if you'd prefer not to 

<img width="1552" alt="Screen Shot 2020-08-20 at 4 47 13 PM" src="https://user-images.githubusercontent.com/11656932/90829505-7b3a9580-e305-11ea-991f-66650a9d245e.png">

**Comment by gjoseph92** [comment]
Will do! Thanks for pointing that out, @jrbourbeau.

**Comment by jrbourbeau** [comment]
Np, thanks for noticing in the first place : )

**Comment by gjoseph92** [comment]
Closing in favor of https://github.com/dask/distributed/issues/4058
