### ISSUE TITLE
Include `gcc` in default docker image

### ISSUE THREAD

**Issue by mrocklin** [coiled/coiled-issues#56]
For people who rely on `pip` to install packages we should probably include a base level of compilers.  Maybe this just means adding `gcc` to our base docker image.

cc @jrbourbeau who I suspect can resolve this.  

cc @shikharsg , who would have found it useful

**Comment by jrbourbeau** [comment]
We've updated our default base image to include `gcc` -- though we haven't deployed these changes yet. The new base docker image lives here https://github.com/coiled/coiled-docker and I'll post on this issue when we've deployed the updates 👍

**Comment by jrbourbeau** [comment]
As of today the default image used for software environment (https://hub.docker.com/r/coiled/default) has `gcc` installed
