### ISSUE TITLE
coiled.yml vs coiled-cloud.yml

### ISSUE THREAD

**Issue by ericdill** [coiled/coiled-issues#58]
What's the canonical coiled config? For whatever reason I seem to have both coiled.yml and coiled-cloud.yml in my ~/.config/dask/ directory. cc @robjcaskey

**Comment by necaris** [comment]
@ericdill @robjcaskey you want `coiled.yml` - `coiled-cloud.yml` is left over from an older version of the `coiled` library :smile:

**Comment by ericdill** [comment]
thx @necaris
