### ISSUE TITLE
Join Us In Slack link doesn't work

### ISSUE THREAD

**Issue by mulka** [coiled/coiled-issues#73]
The link in the Coiled dashboard that says "Join Us In Slack" doesn't work for me. It takes me to a page that says "This link is no longer active"

**Comment by jrbourbeau** [comment]
Thanks for pointing that out @mulka! @necaris is fixing the link right now

**Comment by necaris** [comment]
Just redeployed -- this should now be fixed

**Comment by jrbourbeau** [comment]
Sweet, thanks @necaris! And thanks again @mulka for reporting
