### ISSUE TITLE
KilledWorker reading from ADLS 

### ISSUE THREAD

**Issue by lostmygithubaccount** [coiled/coiled-issues#76]
I consistently get a KilledWorker when trying to print `df.head()` or most other operations on a DataFrame created reading via dask/adlfs, even reading a single column. Any insights into why? 

You can see an example with the full stack trace here: https://github.com/lostmygithubaccount/dasky/blob/coiled/coiled/testing.ipynb

**Comment by mrocklin** [comment]
Hi Cody!  I recommend checking out worker logs.  You can see these by going
to https://cloud.coiled.io/clusters and clicking on the four horizontal
lines to the right of your cluster entry.  The most common cause for this
today is that some library wasn't installed remotely.
