### ISSUE TITLE
ValueError: Unable to update Environment: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by natsunami** [coiled/coiled-issues#88]
Hello ! When creating a new environment like said in the examples:

`coiled.create_software_environment(
    name="ml-env",
    conda={"channels": ["conda-forge"], "dependencies": ["xgboost", "dask"]})`

I get the following error:

ValueError                                Traceback (most recent call last)
<ipython-input-24-affd1f71fe9f> in <module>
----> 1 coiled.create_software_environment(
      2     name="ml-env",
      3     conda={"channels": ["conda-forge"], "dependencies": ["xgboost", "dask"]})

~/anaconda3/lib/python3.8/site-packages/coiled/core.py in create_software_environment(name, conda, pip, container, region, log_output, post_build, conda_env_name, private)
   1285     """
   1286     with Cloud() as cloud:
-> 1287         return cloud.create_software_environment(
   1288             name=name,
   1289             conda=conda,

~/anaconda3/lib/python3.8/site-packages/coiled/core.py in create_software_environment(self, name, conda, pip, container, post_build, conda_env_name, region, log_output, private)
    545         private: bool = False,
    546     ) -> dict:
--> 547         return self._sync(  # type: ignore
    548             self._create_software_environment,
    549             name=name,

~/anaconda3/lib/python3.8/site-packages/coiled/core.py in _sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    279             return future
    280         else:
--> 281             return sync(
    282                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    283             )

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/coiled/core.py in _create_software_environment(self, name, conda, pip, container, post_build, region, conda_env_name, log_output, private)
    646         error_details = await self._websocket_stream(ws, log_output, use_spinner=False)
    647         if error_details:
--> 648             raise ValueError(f"Unable to update Environment: {error_details}")
    649 
    650     async def _list_software_environments(self, account=None):

ValueError: Unable to update Environment: [Errno 12] Cannot allocate memory

Any ideas about what can cause this error ?

Thanks for the help !

**Comment by jrbourbeau** [comment]
Thanks for reporting an issue @natsunami! This may have been an issue on our end. Could I ask you to try creating this software environment again? I was just able to run:

```python
import coiled
coiled.create_software_environment(
    name="ml-env",
    conda={"channels": ["conda-forge"], "dependencies": ["xgboost", "dask"]},
)
```

successfully

**Comment by natsunami** [comment]
Everything work fine now ! Thanks for the help !

**Comment by jrbourbeau** [comment]
No problem, thank you for raising an issue!
