### ISSUE TITLE
User Guide Broken Links/Non-Operational Examples

### ISSUE THREAD

**Issue by StewSchrieff** [coiled/coiled-issues#89]
I ran into a few broken links while looking for some [code examples here](https://docs.coiled.io/user_guide/examples.html). Looks like all of the "Launch Coiled Notebook" links take you to https://cloud.coiled.io/jobs/coiled/xyz. This prompts a login if not currently logged in, but if I am logged in, shows an error message that it cannot find the account "jobs".

It's likely the routing of the websites were rearranged but the docs never got the memo. 😃  

I'd love to see these code examples!

**Comment by mrocklin** [comment]
> It's likely the routing of the websites were rearranged but the docs
never got the memo. 😃

Ha!  indeed

> i'd love to see these code examples!

I think that you're looking for https://cloud.coiled.io/examples/notebooks

**Comment by StewSchrieff** [comment]
Those are definitely the examples I'm looking for!

However, now I'm seeing the following error when trying to launch any of the examples: 

> An error occurred:
> Connection to server closed unexpectedly

I do see there is an "Experimental" tag, so I may have caught the experiment at a bad time.

**Comment by jrbourbeau** [comment]
Hrm, I guess so. Thanks for bringing this to our attention @StewSchrieff! We've updated the links on the "Examples" doc page, and will let you know when we've resolved the error in launching the examples

**Comment by StewSchrieff** [comment]
Thanks for the quick response folks!

I've updated the title of this issue, and will leave this issue open until those examples are working again.

**Comment by jrbourbeau** [comment]
@StewSchrieff I was just able to launch this example notebook https://cloud.coiled.io/examples/jobs/dask-sql successfully. Could you give it another shot and let us know if you still run into an error?

**Comment by mrocklin** [comment]
I suspect that the issue is intermittent.  I think that @necaris is looking
into it.

**Comment by StewSchrieff** [comment]
That certainly sounds possible @mrocklin. For what it's worth, both last night and just now I've been experiencing the same unexpectedly closed issue.

**Comment by jrbourbeau** [comment]
Great! Thank you @StewSchrieff. @necaris were looking into this but couldn't find a relevant error in our backend. I'll go look to see if we can dig further with the error you just encountered.

**Comment by jrbourbeau** [comment]
> Great!

Well...not great, but thanks for trying again : )

**Comment by dantheman39** [comment]
@StewSchrieff we've pushed a change that I hope will fix your issue, if you get a second to try it out again that would be great.

Thanks for reporting your issues, it's very helpful!

**Comment by StewSchrieff** [comment]
@dantheman39 I'm checking on it now, but it appears something else has gone wrong. I see only a blank screen when accessing https://cloud.coiled.io/examples/jobs/dask-sql. I also only see a blank screen when accessing just https://cloud.coiled.io .

I'm not entirely sure what could have caused this, but in the console I do see the following error regarding MIME types. 

>Refused to execute script from 'https://cloud.coiled.io/static/app.472926ea.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I'm not sure if this is directly related to your push @dantheman39, but it seems like it might be.

**Comment by necaris** [comment]
@StewSchrieff looks like you ran into some instability right after our deploy. I've checked it a couple of times lately and it seems more stable now -- are you able to access cloud.coiled.io ?

**Comment by StewSchrieff** [comment]
@necaris Yep, I'm able to access cloud.coiled.io, and the examples appear to be working! 

Thanks all for your help! Closing issue now.

**Comment by jrbourbeau** [comment]
Thanks @StewSchrieff!
